from __future__ import annotations


APP_NAME = "MoodMix"


def song(title: str, artist: str, youtube_id: str | None = None) -> dict:
    return {
        "title": title,
        "artist": artist,
        "youtube_id": youtube_id,
    }


MOOD_LIBRARY = {
    "happy": {
        "label": "Happy",
        "description": "Bright pop, famous rappers, and sing-along energy.",
        "fallback_video_id": "ZbZSe6N_BXs",
        "songs": [
            song("Happy", "Pharrell Williams", "ZbZSe6N_BXs"),
            song("Shake It Off", "Taylor Swift", "nfWlot6h_JM"),
            song("Uptown Funk", "Mark Ronson ft. Bruno Mars", "OPf0YbXqDm0"),
            song("Can't Stop the Feeling!", "Justin Timberlake", "ru0K8uYEZWw"),
            song("I Gotta Feeling", "The Black Eyed Peas"),
            song("Hey Ya!", "OutKast", "PWgvGjAhvIw"),
            song("Can't Hold Us", "Macklemore & Ryan Lewis ft. Ray Dalton", "2zNSgSzhBfM"),
            song("24K Magic", "Bruno Mars", "UqyT8IEBkvY"),
            song("About Damn Time", "Lizzo", "IXXxciRUMzE"),
            song("Good as Hell", "Lizzo", "vuq-VAiW9kw"),
            song("Good Life", "Kanye West ft. T-Pain"),
            song("Good Day", "Nappy Roots"),
            song("Sunflower", "Post Malone & Swae Lee"),
            song("Levitating", "Dua Lipa"),
            song("BIRDS OF A FEATHER", "Billie Eilish"),
            song("Treasure", "Bruno Mars"),
            song("Shut Up and Dance", "WALK THE MOON"),
            song("Cake By The Ocean", "DNCE"),
            song("Walking on Sunshine", "Katrina and the Waves"),
            song("Best Day of My Life", "American Authors"),
            song("Dynamite", "BTS"),
            song("Espresso", "Sabrina Carpenter"),
            song("Blinding Lights", "The Weeknd"),
            song("Starships", "Nicki Minaj", "SeIJmciN8mo"),
            song("Party in the U.S.A.", "Miley Cyrus"),
            song("On Top of the World", "Imagine Dragons"),
        ],
    },
    "confident": {
        "label": "Confident",
        "description": "Main-character music, swagger, and big-walk energy.",
        "fallback_video_id": "SeIJmciN8mo",
        "songs": [
            song("Run the World (Girls)", "Beyonce", "VBmMU_iwe6U"),
            song("Formation", "Beyonce"),
            song("7 rings", "Ariana Grande"),
            song("Starships", "Nicki Minaj", "SeIJmciN8mo"),
            song("Stronger", "Kanye West", "PsO6ZnUZI0g"),
            song("DNA.", "Kendrick Lamar", "NLZRYQMLDW4"),
            song("POWER", "Kanye West"),
            song("Savage Remix", "Megan Thee Stallion ft. Beyonce"),
            song("Boss Bitch", "Doja Cat"),
            song("Good as Hell", "Lizzo", "vuq-VAiW9kw"),
            song("Money", "Cardi B"),
            song("God's Plan", "Drake"),
            song("Bodak Yellow", "Cardi B"),
            song("Super Bass", "Nicki Minaj"),
            song("Woman", "Doja Cat"),
            song("Say So", "Doja Cat"),
            song("Needed Me", "Rihanna"),
            song("Big Energy", "Latto"),
            song("Empire State of Mind", "Jay-Z ft. Alicia Keys"),
            song("HUMBLE.", "Kendrick Lamar"),
            song("All the Stars", "Kendrick Lamar & SZA"),
            song("Flawless", "Beyonce"),
            song("Rich Flex", "Drake & 21 Savage"),
            song("Barbie World", "Nicki Minaj & Ice Spice"),
            song("Anaconda", "Nicki Minaj"),
            song("Alien Superstar", "Beyonce"),
        ],
    },
    "chill": {
        "label": "Chill",
        "description": "Soft R&B, dreamy pop, and relaxed late-night vibes.",
        "fallback_video_id": "viimfQi_pUw",
        "songs": [
            song("Ocean Eyes", "Billie Eilish", "viimfQi_pUw"),
            song("BIRDS OF A FEATHER", "Billie Eilish"),
            song("Sunflower", "Post Malone & Swae Lee"),
            song("Electric Feel", "MGMT"),
            song("Location", "Khalid"),
            song("Snooze", "SZA"),
            song("Stay", "Rihanna ft. Mikky Ekko", "JF8BRvqGCNs"),
            song("telepatia", "Kali Uchis"),
            song("Best Part", "Daniel Caesar ft. H.E.R."),
            song("Peaches", "Justin Bieber ft. Daniel Caesar & Giveon"),
            song("golden hour", "JVKE"),
            song("Pink + White", "Frank Ocean"),
            song("See You Again", "Tyler, The Creator ft. Kali Uchis"),
            song("Moonlight", "Kali Uchis"),
            song("Earned It", "The Weeknd"),
            song("Passionfruit", "Drake"),
            song("After the Storm", "Kali Uchis ft. Tyler, The Creator & Bootsy Collins"),
            song("Sweater Weather", "The Neighbourhood"),
            song("Redbone", "Childish Gambino"),
            song("Love Galore", "SZA ft. Travis Scott"),
            song("The Less I Know the Better", "Tame Impala"),
            song("Cigarette Daydreams", "Cage the Elephant"),
            song("Space Song", "Beach House"),
            song("Glue Song", "beabadoobee"),
            song("Saturn", "SZA"),
            song("Adorn", "Miguel"),
        ],
    },
    "sad": {
        "label": "Sad",
        "description": "Emotional songs for heartbreak, healing, and reflection.",
        "fallback_video_id": "hLQl3WQQoQ0",
        "songs": [
            song("Someone Like You", "Adele", "hLQl3WQQoQ0"),
            song("Let Her Go", "Passenger", "RBumgq5yVrA"),
            song("All I Want", "Kodaline", "mtf7hC17IBM"),
            song("drivers license", "Olivia Rodrigo"),
            song("Lovely", "Billie Eilish & Khalid"),
            song("Happier", "Ed Sheeran"),
            song("when the party's over", "Billie Eilish"),
            song("traitor", "Olivia Rodrigo"),
            song("Easy On Me", "Adele"),
            song("Glimpse of Us", "Joji"),
            song("Heather", "Conan Gray"),
            song("Skinny Love", "Bon Iver"),
            song("Say Something", "A Great Big World & Christina Aguilera"),
            song("Fix You", "Coldplay"),
            song("Lose You to Love Me", "Selena Gomez"),
            song("idontwannabeyouanymore", "Billie Eilish"),
            song("The Night We Met", "Lord Huron"),
            song("Liability", "Lorde"),
            song("Before You Go", "Lewis Capaldi"),
            song("favorite crime", "Olivia Rodrigo"),
            song("Arcade", "Duncan Laurence"),
            song("If the World Was Ending", "JP Saxe ft. Julia Michaels"),
            song("Back to Black", "Amy Winehouse"),
            song("everything i wanted", "Billie Eilish"),
            song("When I Was Your Man", "Bruno Mars"),
            song("Stone Cold", "Demi Lovato"),
        ],
    },
    "tired": {
        "label": "Tired",
        "description": "Quiet reset music for rest, recovery, and slow evenings.",
        "fallback_video_id": "5qap5aO4i9A",
        "songs": [
            song("Lo-fi Beats", "Lo-fi stream", "5qap5aO4i9A"),
            song("Weightless Relax", "Ambient", "UfcAVejslrU"),
            song("Calm Piano", "Instrumental", "1ZYbU82GVz4"),
            song("Deep Sleep Music", "Relaxation", "2OEL4P1Rz04"),
            song("Lovely", "Billie Eilish & Khalid"),
            song("Come Away With Me", "Norah Jones"),
            song("Holocene", "Bon Iver"),
            song("Bloom", "The Paper Kites"),
            song("Night Trouble", "Petit Biscuit"),
            song("Saturn", "SZA"),
            song("Moon Song", "Phoebe Bridgers"),
            song("Slow Burn", "Kacey Musgraves"),
            song("Malibu Nights", "LANY"),
            song("Breathe Me", "Sia"),
            song("River Flows in You", "Yiruma"),
            song("Sunset Lover", "Petit Biscuit"),
            song("Mystery of Love", "Sufjan Stevens"),
            song("Ribs", "Lorde"),
            song("exile", "Taylor Swift ft. Bon Iver"),
            song("White Ferrari", "Frank Ocean"),
            song("Vienna", "Billy Joel"),
            song("Yellow", "Coldplay"),
            song("Falling", "Harry Styles"),
            song("cardigan", "Taylor Swift"),
            song("Apocalypse", "Cigarettes After Sex"),
            song("Ocean Eyes", "Billie Eilish", "viimfQi_pUw"),
        ],
    },
    "angry": {
        "label": "Angry",
        "description": "Intense rap, heavy drums, and songs to channel pressure.",
        "fallback_video_id": "_Yhyp-_hX2s",
        "songs": [
            song("Lose Yourself", "Eminem", "_Yhyp-_hX2s"),
            song("Believer", "Imagine Dragons", "7wtfhZwyrcc"),
            song("DNA.", "Kendrick Lamar", "NLZRYQMLDW4"),
            song("SICKO MODE", "Travis Scott"),
            song("POWER", "Kanye West"),
            song("HUMBLE.", "Kendrick Lamar"),
            song("Till I Collapse", "Eminem"),
            song("Black Skinhead", "Kanye West"),
            song("N95", "Kendrick Lamar"),
            song("X Gon' Give It To Ya", "DMX"),
            song("Remember the Name", "Fort Minor"),
            song("Can't Be Touched", "Roy Jones Jr."),
            song("Mask Off", "Future"),
            song("No Church in the Wild", "Jay-Z & Kanye West ft. Frank Ocean"),
            song("Backseat Freestyle", "Kendrick Lamar"),
            song("Look At Me!", "XXXTENTACION"),
            song("goosebumps", "Travis Scott"),
            song("First Person Shooter", "Drake ft. J. Cole"),
            song("HYAENA", "Travis Scott"),
            song("Radioactive", "Imagine Dragons"),
            song("Monster", "Skillet"),
            song("Whatever It Takes", "Imagine Dragons"),
            song("INDUSTRY BABY", "Lil Nas X & Jack Harlow"),
            song("Fight Music", "D12"),
            song("Many Men", "50 Cent"),
            song("m.A.A.d city", "Kendrick Lamar"),
        ],
    },
    "romantic": {
        "label": "Romantic",
        "description": "Warm, soft, and dreamy songs for love and crush moods.",
        "fallback_video_id": "JF8BRvqGCNs",
        "songs": [
            song("Perfect", "Ed Sheeran"),
            song("Adore You", "Harry Styles"),
            song("Best Part", "Daniel Caesar ft. H.E.R."),
            song("All of Me", "John Legend"),
            song("Love on the Brain", "Rihanna"),
            song("Die With A Smile", "Lady Gaga & Bruno Mars"),
            song("Until I Found You", "Stephen Sanchez"),
            song("Can I Call You Rose?", "Thee Sacred Souls"),
            song("Earned It", "The Weeknd"),
            song("Love Galore", "SZA ft. Travis Scott"),
            song("Teenage Dream", "Katy Perry"),
            song("Love Me Like You Do", "Ellie Goulding"),
            song("Kiss Me", "Sixpence None the Richer"),
            song("Lover", "Taylor Swift"),
            song("Just the Way You Are", "Bruno Mars"),
            song("Yellow", "Coldplay"),
            song("Die For You", "The Weeknd"),
            song("Dandelions", "Ruth B."),
            song("Iris", "The Goo Goo Dolls"),
            song("Make You Feel My Love", "Adele"),
            song("A Thousand Years", "Christina Perri"),
            song("Speechless", "Dan + Shay"),
            song("Can't Help Falling in Love", "Elvis Presley"),
            song("Put Your Head on My Shoulder", "Paul Anka"),
            song("My Love Mine All Mine", "Mitski"),
            song("Halo", "Beyonce"),
        ],
    },
    "focus": {
        "label": "Focus",
        "description": "Steady study music, smooth beats, and locked-in concentration.",
        "fallback_video_id": "5qap5aO4i9A",
        "songs": [
            song("Lo-fi Beats", "Lo-fi stream", "5qap5aO4i9A"),
            song("Sunset Lover", "Petit Biscuit"),
            song("Midnight City", "M83"),
            song("Innerbloom", "RUFUS DU SOL"),
            song("Nights", "Frank Ocean"),
            song("After Dark", "Mr.Kitty"),
            song("Intro", "The xx"),
            song("Space Song", "Beach House"),
            song("Get You the Moon", "Kina ft. Snow"),
            song("Young and Beautiful", "Lana Del Rey"),
            song("See You Again", "Tyler, The Creator ft. Kali Uchis"),
            song("Money Trees", "Kendrick Lamar ft. Jay Rock"),
            song("Daylight", "David Kushner"),
            song("Swim Good", "Frank Ocean"),
            song("White Ferrari", "Frank Ocean"),
            song("505", "Arctic Monkeys"),
            song("The Night We Met", "Lord Huron"),
            song("Pink + White", "Frank Ocean"),
            song("Open Arms", "SZA ft. Travis Scott"),
            song("Crew Love", "Drake ft. The Weeknd"),
            song("Pursuit of Happiness", "Kid Cudi"),
            song("STARGAZING", "Travis Scott"),
            song("telepatia", "Kali Uchis"),
            song("Runaway", "Kanye West"),
            song("Redbone", "Childish Gambino"),
            song("Feels Like We Only Go Backwards", "Tame Impala"),
        ],
    },
}
